server:
  port: 8082
spring:
  application:
    name: S9user
  cloud:
    discovery:
      enabled: true
eureka:
  instance:
    hostname: localhost

# actuator
info:
  app:
    name: "seminar_11_prometheus_grafana"
    version: "1.0.0"
    description: "seminar11 user service"

management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
          status:
            http-mapping:
              up: 207
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true